### ISSUE TITLE
frontera throws an exception

### ISSUE THREAD

**Issue by voith** [vy-labs/frontera#30]
```
Unhandled Error
Traceback (most recent call last):
  File "/Users/voith/Projects/crawler_app/sridhar/lib/python2.7/site-packages/scrapy/commands/crawl.py", line 58, in run
    self.crawler_process.start()
  File "/Users/voith/Projects/crawler_app/sridhar/lib/python2.7/site-packages/scrapy/crawler.py", line 251, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "/Users/voith/Projects/crawler_app/sridhar/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/Users/voith/Projects/crawler_app/sridhar/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/Users/voith/Projects/crawler_app/sridhar/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/Users/voith/Projects/crawler_app/sridhar/lib/python2.7/site-packages/scrapy/utils/reactor.py", line 41, in __call__
    return self._func(*self._a, **self._kw)
  File "/Users/voith/Projects/crawler_app/sridhar/lib/python2.7/site-packages/scrapy/core/engine.py", line 105, in _next_request
    if not self._next_request_from_scheduler(spider):
  File "/Users/voith/Projects/crawler_app/sridhar/lib/python2.7/site-packages/scrapy/core/engine.py", line 132, in _next_request_from_scheduler
    request = slot.scheduler.next_request()
  File "/Users/voith/Projects/crawler_app/sridhar/src/frontera-feature-production/frontera/contrib/scrapy/schedulers/frontier.py", line 100, in next_request
    request = self._get_next_request()
  File "/Users/voith/Projects/crawler_app/sridhar/src/frontera-feature-production/frontera/contrib/scrapy/schedulers/frontier.py", line 155, in _get_next_request
    requests = self.frontier.get_next_requests(key_type=info['key_type'], overused_keys=info['overused_keys'])
  File "/Users/voith/Projects/crawler_app/sridhar/src/frontera-feature-production/frontera/utils/managers.py", line 29, in get_next_requests
    frontier_requests = self.manager.get_next_requests(max_next_requests=max_next_requests, **kwargs)
  File "/Users/voith/Projects/crawler_app/sridhar/src/frontera-feature-production/frontera/core/manager.py", line 427, in get_next_requests
    next_requests = self.backend.get_next_requests(max_next_requests, **kwargs)
  File "/Users/voith/Projects/crawler_app/sridhar/src/frontera-feature-production/frontera/contrib/backends/sqlalchemy/__init__.py", line 200, in get_next_requests
    for db_page in query:
  File "/Users/voith/Projects/crawler_app/sridhar/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 90, in instances
    util.raise_from_cause(err)
  File "/Users/voith/Projects/crawler_app/sridhar/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/voith/Projects/crawler_app/sridhar/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 75, in instances
    rows = [proc(row) for row in fetch]
  File "/Users/voith/Projects/crawler_app/sridhar/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 469, in _instance
    unloaded, populators)
  File "/Users/voith/Projects/crawler_app/sridhar/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 554, in _populate_partial
    dict_[key] = getter(row)
  File "/Users/voith/Projects/crawler_app/sridhar/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1478, in process
    return loads(value)
exceptions.EOFError:
```

**Comment by voith** [comment]
Looks like this happens when size of meta is very large. In Mysql PickleType resolves to blob which has a size of 65,535 (216 – 1) bytes
