### ISSUE TITLE
sqlalchemy backend has an unhandled deadlock condition

### ISSUE THREAD

**Issue by voith** [vy-labs/frontera#33]
here's the traceback:
```
2017-05-03 10:52:26+0000 [Launcher,1416/stderr] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/commands/crawl.py", line 58, in run
	    self.crawler_process.start()
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 251, in start
	    reactor.run(installSignalHandlers=False)  # blocking call
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
	    self.mainLoop()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/reactor.py", line 41, in __call__
	    return self._func(*self._a, **self._kw)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/engine.py", line 105, in _next_request
	    if not self._next_request_from_scheduler(spider):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/engine.py", line 132, in _next_request_from_scheduler
	    request = slot.scheduler.next_request()
	  File "/home/ubuntu/src/frontera-feature-production/frontera/contrib/scrapy/schedulers/frontier.py", line 100, in next_request
	    request = self._get_next_request()
	  File "/home/ubuntu/src/frontera-feature-production/frontera/contrib/scrapy/schedulers/frontier.py", line 155, in _get_next_request
	    requests = self.frontier.get_next_requests(key_type=info['key_type'], overused_keys=info['overused_keys'])
	  File "/home/ubuntu/src/frontera-feature-production/frontera/utils/managers.py", line 29, in get_next_requests
	    frontier_requests = self.manager.get_next_requests(max_next_requests=max_next_requests, **kwargs)
	  File "/home/ubuntu/src/frontera-feature-production/frontera/core/manager.py", line 427, in get_next_requests
	    next_requests = self.backend.get_next_requests(max_next_requests, **kwargs)
	  File "/home/ubuntu/src/frontera-feature-production/frontera/contrib/backends/sqlalchemy/__init__.py", line 200, in get_next_requests
	    for db_page in query:
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2797, in __iter__
	    return self._execute_and_instances(context)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2820, in _execute_and_instances
	    result = conn.execute(querycontext.statement, self._params)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
	    return meth(self, multiparams, params)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
	    return connection._execute_clauseelement(self, multiparams, params)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
	    compiled_sql, distilled_params
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
	    context)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
	    exc_info
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
	    reraise(type(exception), exception, tb=exc_tb, cause=cause)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
	    context)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 469, in do_execute
	    cursor.execute(statement, parameters)
	  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1213, 'Deadlock found when trying to get lock; try restarting transaction') [SQL: u'SELECT `7d39a282990740a5953d4fc2519d5d`.url AS `7d39a282990740a5953d4fc2519d5d_url`, `7d39a282990740a5953d4fc2519d5d`.fingerprint AS `7d39a282990740a5953d4fc2519d5d_fingerprint`, `7d39a282990740a5953d4fc2519d5d`.depth AS `7d39a282990740a5953d4fc2519d5d_depth`, `7d39a282990740a5953d4fc2519d5d`.created_at AS `7d39a282990740a5953d4fc2519d5d_created_at`, `7d39a282990740a5953d4fc2519d5d`.status_code AS `7d39a282990740a5953d4fc2519d5d_status_code`, `7d39a282990740a5953d4fc2519d5d`.state AS `7d39a282990740a5953d4fc2519d5d_state`, `7d39a282990740a5953d4fc2519d5d`.error AS `7d39a282990740a5953d4fc2519d5d_error`, `7d39a282990740a5953d4fc2519d5d`.meta AS `7d39a282990740a5953d4fc2519d5d_meta`, `7d39a282990740a5953d4fc2519d5d`.headers AS `7d39a282990740a5953d4fc2519d5d_headers`, `7d39a282990740a5953d4fc2519d5d`.cookies AS `7d39a282990740a5953d4fc2519d5d_cookies`, `7d39a282990740a5953d4fc2519d5d`.method AS `7d39a282990740a5953d4fc2519d5d_method`, `7d39a282990740a5953d4fc2519d5d`.body AS `7d39a282990740a5953d4fc2519d5d_body`, `7d39a282990740a5953d4fc2519d5d`.retries AS `7d39a282990740a5953d4fc2519d5d_retries` \nFROM `7d39a282990740a5953d4fc2519d5d` \nWHERE (`7d39a282990740a5953d4fc2519d5d`.state = %s AND `7d39a282990740a5953d4fc2519d5d`.error IN (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) AND `7d39a282990740a5953d4fc2519d5d`.retries < %s) OR (`7d39a282990740a5953d4fc2519d5d`.state = %s AND `7d39a282990740a5953d4fc2519d5d`.status_code IN (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s) AND `7d39a282990740a5953d4fc2519d5d`.retries < %s) OR (`7d39a282990740a5953d4fc2519d5d`.state = %s) ORDER BY `7d39a282990740a5953d4fc2519d5d`.created_at \n LIMIT %s FOR UPDATE'] [parameters: ('ERROR', 'TimeoutError', 'DNSLookupError', 'ConnectionRefusedError', 'ConnectionDone', 'ConnectError', 'ConnectionLost', 'TCPTimedOutError', 'ResponseFailed', 'IOError', 'NotSupported', 'TunnelError', 'ResponseNeverReceived', 4, 'ERROR', '500', '502', '503', '504', '400', '403', '408', '407', '302', '404', 4, 'NOT CRAWLED', 50)]
```

**Comment by voith** [comment]
fixed in https://github.com/vy-labs/frontera/pull/38/
